Update Release.yml

diff --git a/.github/workflows/Release.yml b/.github/workflows/Release.yml
--- a/.github/workflows/Release.yml
+++ b/.github/workflows/Release.yml
@@ -35,9 +35,18 @@ jobs:
 
       - name: Replace values on appsettings.json
         shell: bash
+        env:
+          TOKEN: ${{ secrets.BETTERSTACK_SOURCE_TOKEN }}
+          ENDPOINT: ${{ secrets.BETTERSTACK_ENDPOINT }}
         run: |
-          sed -i "" 's|"sourceToken": "[^"]*"|"sourceToken": "${{ secrets.BETTERSTACK_SOURCE_TOKEN }}"|' "${{ github.workspace }}\EasyFinance.Server\bin\Release\net8.0\publish\appsettings.json"
-          sed -i "" 's|"betterStackEndpoint": "[^"]*"|"betterStackEndpoint": "${{ secrets.BETTERSTACK_ENDPOINT }}"|' "${{ github.workspace }}\EasyFinance.Server\bin\Release\net8.0\publish\appsettings.json"
+          FILE="${{ github.workspace }}/EasyFinance.Server/bin/Release/net8.0/publish/appsettings.json"
+          if [ ! -f "$FILE" ]; then
+            echo "File not found: $FILE"
+            exit 1
+          fi
+      
+          sed -i -E "s|\"sourceToken\"\s*:\s*\"[^\"]*\"|\"sourceToken\": \"${TOKEN}\"|" "$FILE"
+          sed -i -E "s|\"betterStackEndpoint\"\s*:\s*\"[^\"]*\"|\"betterStackEndpoint\": \"${ENDPOINT}\"|" "$FILE"
           
       - name: Deploy
         uses: ChristopheLav/iis-deploy@v1
